### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by Giancarmine**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Awesome, thank you so much for your help @Giancarmine! 👍

**Comment by CrazyMarvin** [comment]
May you please put the translation on [Crowdin](https://crowdin.com/project/flashy) too?

**Comment by Giancarmine** [comment]
[Crowdin](https://crowdin.com/project/flashy/it#) updated :rocket: 
Please check out this to [hacktoberfest-update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by CrazyMarvin** [comment]
Thank you so much. It worked. 😎
This repo should be Hacktoberfest-ready. Does your [dashboard](http://hacktoberfest.digitalocean.com/) say something else?

**Comment by CrazyMarvin** [comment]
If you like you can translate [Pimple Popper](https://github.com/Crazy-Marvin/PimplePopper/tree/development/fastlane/metadata/android/it-IT) into Italian too. 😉

**Comment by Giancarmine** [comment]
Look nice :+1:

**Pull request merged**
