### PR TITLE
Added Filipino Translations

### PR DESCRIPTION
**Pull request by chesfire**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Awesome, thank you for your help @gutchaman! 👍

**Comment by CrazyMarvin** [comment]
May you please put the translation on [Crowdin](https://crowdin.com/project/flashy) too?

**Comment by chesfire** [comment]
your welcome! im sorry but i dont know how to use crowdin

**Comment by CrazyMarvin** [comment]
You can follow the [link](https://crowdin.com/project/flashy/fil#) and signup with your GitHub account. Then you choose the Filipino language and an editor opens. 
I think the process is quite straightforward. Please have a look.

**Comment by chesfire** [comment]
I just edited now on crowdin!

**Comment by CrazyMarvin** [comment]
Thanks! 😎

**Pull request merged**
