### PR TITLE
Some improvements

### LINKED ISSUE #41: Avoid Camera permission
Other flashlight apps like Simple Flashlight work without Camera permission, so there seems to be a way to control the flashlight w/o Camera permission. For an app like Flashy that claims to be privacy friendly it would be good to use such less intrusive permissions or state why Camera permission is necessary.

### PR DESCRIPTION
**Pull request by unbiaseduser**
Hello! I have known about your organization from F-Droid and I decided to contribute to this app.
 Specifically, I made these improvements:
- App does not need Camera permission on Android 6+ anymore. Fixes #41. 
- The dialog that shows when device has no camera now switches back to screen brightness mode on being dismissed, instead of only when clicking the button (like before).
That's it for now. I hope to hear back from you soon.

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Hey, @unbiaseduser! Thank you so much for your PR. I highly appreciate it as I did not find time to improve the app for quite some time. You're awesome!
@FahadSaleem, do you have any objections to merge this?

**Review by CrazyMarvin — APPROVED** [review]
LGTM

**Comment by unbiaseduser** [comment]
You're welcome. Unfortunately, I don't think that the original maintainer (@FahadSaleem) is active anymore. So, my changes will probably never get merged if everything depends on them.
Also, today I have added a Quick Settings tile (fixes #10). **_I can't add a new commit without it also showing up here, so... I guess I'll comment on this PR instead..._**

**Comment by FahadSaleem** [comment]
I'll take a look at this quickly and get back to you !

**Comment by unbiaseduser** [comment]
So, after some time, I have implemented a toggle widget as well. (#27) I think I'm done for today, you can take your time reviewing my changes. I'll come back when you're finished.

**Comment by unbiaseduser** [comment]
So @FahadSaleem any updates so far? If you have any questions I'm always ready to answer.
Are you still active? If not then I understand... Just that I really want to do something great for the project. :(

**Comment by CrazyMarvin** [comment]
Don't worry, @unbiaseduser. If @FahadSaleem does not find time to check your PR this week, I will merge it.

**Comment by unbiaseduser** [comment]
I just fixed #53. Anyway, @CrazyMarvin when will the new version be released?
Also, I would like to become a maintainer for this project, in case @FahadSaleem does not return.

**Comment by FahadSaleem** [comment]
I've checked this. Looks good to me @CrazyMarvin the codacy check fails just to let you know

**Comment by CrazyMarvin** [comment]
Thank you very much.
I will prepare the release today.

**Comment by FahadSaleem** [comment]
Hi, I'm active. I'll have a look at your changes very soon.

**Pull request merged**
