### PR TITLE
add about page

### LINKED ISSUE #61: Feedback on upcoming About page
I'm making an About page for the app, and I'd like to show the UI I made. This is just a draft, I'll change it if you have a good suggestion. Do provide feedback, please. @CrazyMarvin @FahadSaleem
Screenshot_20221003-233040832

### PR DESCRIPTION
**Pull request by unbiaseduser**
Can we close #61 now?

### CODE REVIEW

**Comment by unbiaseduser** [comment]
@CrazyMarvin Everything's alright?

**Comment by CrazyMarvin** [comment]
For what is this string needed?

` <string name="no_app_can_handle">No app can handle this action.</string>`

**Comment by unbiaseduser** [comment]
For if a browser or email app is not available?

**Comment by CrazyMarvin** [comment]
I see, that's good. 👍

**Comment by CrazyMarvin** [comment]
Thank you very much! 😊

**Pull request merged**
