### PR TITLE
Added Colourful Screen

### PR DESCRIPTION
**Pull request by prathamesh-2002**
Added option in settings to change screen light colour #35

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Thank you very much for your support, @prathamesh-2002! 👍

What do you think about this, @unbiaseduser?

I am not sure if we should use fixed colors or offer a color picker. 🤔

**Comment by prathamesh-2002** [comment]
There is no in-built library for colour picker so I gave options of some bright colours there for now, but yeah I can integrate a third party colour picker later.

**Comment by unbiaseduser** [comment]
@prathamesh-2002 Some feedback:
- Move the `applyColourFromSettings` method to the `Utils` class, since that's where static utility methods go
- In the `MainActivity`, remove the comment
`//force set white, because it does not make sense for the app to be dark when using screen light`
since it is not true now
Also, if you're going to use a third party color picker, I recommend https://github.com/Dhaval2404/ColorPicker
since it offers both a color wheel and a simple color array. So you can implement two different color picker modes.

**Comment by CrazyMarvin** [comment]
> @prathamesh-2002 Some feedback:
> - Move the `applyColourFromSettings` method to the `Utils` class, since that's where static utility methods go
> - In the `MainActivity`, remove the comment
> `//force set white, because it does not make sense for the app to be dark when using screen light`
> since it is not true now
> Also, if you're going to use a third party color picker, I recommend https://github.com/Dhaval2404/ColorPicker
> since it offers both a color wheel and a simple color array. So you can implement two different color picker modes.

Thanks for the feedback. 👍

**Comment by CrazyMarvin** [comment]
@prathamesh-2002, do you have time to update this PR this week?

**Comment by prathamesh-2002** [comment]
yeah, i'll try to update by this weekend

**Comment by CrazyMarvin** [comment]
> yeah, i'll try to update by this weekend

Do you have time to send an updated PR this month, @prathamesh-2002?
I will try to create a new release next month.

**Pull request closed without merging**
