### PR TITLE
Material 3 setting + miscellaneous code maintenance

### PR DESCRIPTION
**Pull request by unbiaseduser**
I added a setting to use [Material Design 3](https://m3.material.io/) as well as some refactoring:
- Separate files into folders for easier maintenance
- Reduce number of `Views` in main screen to improve performance
- Fix some code design

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
This is awesome!

**Comment by unbiaseduser** [comment]
Oh. Oh no.
**_Do I have to wait like, a week for my changes to be merged again?_**
Also @FahadSaleem if you're coming back, please be quick to manage your project, or else you'll just create a massive bottleneck.

**Comment by CrazyMarvin** [comment]
> Oh. Oh no.
> **_Do I have to wait like, a week for my changes to be merged again?_**
> Also @FahadSaleem if you're coming back, please be quick to manage your project, or else you'll just create a massive bottleneck.

Don't worry, I will merge your PR in case Fahad is busy.
As this is just a hobby project it does not have the highest priority and reactions may not be immediately.

**Comment by unbiaseduser** [comment]
> > Oh. Oh no.
> > **_Do I have to wait like, a week for my changes to be merged again?_**
> > Also @FahadSaleem if you're coming back, please be quick to manage your project, or else you'll just create a massive bottleneck.
> 
> Don't worry, I will merge your PR in case Fahad is busy. As this is just a hobby project it does not have the highest priority and reactions may not be immediately.

I'm sorry if I sound a bit harsh, but that's just the truth. And the truth always hurts. Really, if we keep waiting for Fahad to return, development would stall quite a bit :( Btw @FahadSaleem if you're reading this, please tell me what you think about this.

**Pull request merged**
