### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by Wdestroier**
I added the translation to the portuguese language (pt-BR).

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Awesome, thank you so much for your help @Wdestroier! 👍

**Comment by CrazyMarvin** [comment]
May you please put the translation on [Crowdin](https://crowdin.com/project/flashy) too?

**Comment by Wdestroier** [comment]
Hi! @CrazyMarvin I just did it

**Comment by CrazyMarvin** [comment]
Wonderful, thanks again!

**Pull request merged**
