### PR TITLE
ru_RU locale

### PR DESCRIPTION
**Pull request by Haarolean**
Hey,

I've prepared some i18n for ru_RU. 

Notes:
I've omitted 'under the hood' from the changelog since that's probably not clear what it means for most of users lol.
Also, I don't think that 'fastlane setup' means anything for them as well, but I just translated it as is.

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Awesome, thank you so much for your help @Haarolean! 👍

**Comment by CrazyMarvin** [comment]
May you please put the translation on [Crowdin](https://crowdin.com/project/flashy) too?

**Comment by Haarolean** [comment]
@CrazyMarvin Yeah, I guess. How do I start? All the buttons are disabled for me there.

**Comment by CrazyMarvin** [comment]
Oh sorry, that's my fault. I forgot to setup the Google Play integration on Crowdin. 🙈
Please try again.

**Comment by Haarolean** [comment]
@CrazyMarvin done I guess.

**Pull request merged**
